### ISSUE TITLE
Opportunity for Collaboration

### ISSUE THREAD

**Issue by starglow-it** [sadman400/product_management#1]

**Comment by sadman400** [comment]
Hi Brandon,
Thank you for reaching out and for your kind words. I would love to discuss this opportunity further, let's do a video call today at 10 pm GMT. feel free to share the time that works best for you.
Thank you,
Sadman Hossain

**Comment by sadman400** [comment]
Hi Brandon,
Thank you for reaching out and for your kind words. I would love to discuss
this opportunity further, let's do a video call today at 10 pm GMT. feel
free to share the time that works best for you.
Thank you,
Sadman Hossain
